### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by thiagodemellobueno** [nhoss2/nodewiki#26]
I think there is lots of promise here, and it solves issues for a variety of use cases.
With some polish and attention it could really thrive.

Whats the current state of the project? Is it actively developed?

**Comment by nhoss2** [comment]
I haven't worked on this for a few months, but I was working on a complete rewrite thats on the `newwiki` branch. Right now, work and other projects are keeping me pretty busy but I hope to get back to this sometime, no guarantees on any timing though.

**Comment by thiagodemellobueno** [comment]
I will check out the action on that other repo, thanks.
It's certainly promising.
